In [1]:
import tensorflow as tf
import numpy as np

In [2]:
constan = tf.constant([[1,2,3,4,5,6,7,8,9]], shape=[3,3], dtype=tf.int64)

In [3]:
print(constan)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int64)


In [4]:
zeros = tf.zeros(shape=[3,3], dtype=tf.float32, name=None)

In [5]:
print(zeros)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [6]:
fill = tf.fill([3,3], 8)

In [7]:
print(fill)

tf.Tensor(
[[8 8 8]
 [8 8 8]
 [8 8 8]], shape=(3, 3), dtype=int32)


In [8]:
random = tf.random.normal([5,5],mean=5,stddev=2.1, seed = 1)

In [9]:
print(random)

tf.Tensor(
[[ 3.2962317   8.117657    5.137192   -0.12967873  5.2084217 ]
 [ 6.241571    6.2449284   0.5418482   3.481916    4.881832  ]
 [ 6.3514442   4.4449196   8.89893     6.1924677   4.196045  ]
 [ 1.880779    7.649719    4.9468575   4.444278    8.218908  ]
 [ 1.3397481   4.080425    3.811379    5.6734056   7.378945  ]], shape=(5, 5), dtype=float32)


In [10]:
list = [[1,2,3,4,5,6],[1,2,3,4,5,6]
,[1,2,3,4,5,6]]

In [11]:
tensorto = tf.convert_to_tensor(list, dtype=tf.int64)

In [12]:
print(tensorto)

tf.Tensor(
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]], shape=(3, 6), dtype=int64)


In [13]:
var_ten = tf.Variable(tf.ones([3,3]))

In [14]:
print(var_ten)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>


In [15]:
print("Value of the variabel var_ten:", var_ten.read_value())

Value of the variabel var_ten: tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [16]:
var_ten_val = [[1,2,3],[4,5,6],[7,8,9]]
var_ten.assign(var_ten_val)
print("Value of the variabel 1 after assingment: ", var_ten.read_value())

Value of the variabel 1 after assingment:  tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)


In [17]:
print("Create a 4-dimensional tensor. The tensor contains four images. The size of each image is 100 x 100 x 3.")

Create a 4-dimensional tensor. The tensor contains four images. The size of each image is 100 x 100 x 3.


In [70]:
tensor_h = tf.random.normal([16,16,32,32,64])

In [71]:
tensor_h

<tf.Tensor: shape=(16, 16, 32, 32, 64), dtype=float32, numpy=
array([[[[[-5.35519719e-01, -1.94045782e-01, -6.82630062e-01, ...,
           -9.21371579e-01, -5.92916191e-01,  1.94107875e-01],
          [-2.57627636e-01,  4.79677707e-01, -1.44350362e+00, ...,
            1.08738828e+00, -8.64797652e-01, -1.43983531e+00],
          [-6.91202134e-02, -7.77210236e-01, -1.88712823e+00, ...,
           -6.94596171e-01,  9.76229072e-01, -1.82068133e+00],
          ...,
          [-4.18410659e-01, -5.66869676e-01,  6.99537635e-01, ...,
            1.59400034e+00, -2.89482802e-01,  4.36192721e-01],
          [-2.40126586e+00,  1.47403204e+00, -1.26963866e+00, ...,
            4.30622369e-01,  3.64244491e-01,  7.66551673e-01],
          [-3.71637195e-01, -1.74506152e+00,  3.13107848e-01, ...,
            3.47942948e-01, -1.06446661e-01,  1.08309709e-01]],

         [[ 5.04871130e-01, -1.32033527e+00, -1.09513474e+00, ...,
           -2.08824322e-01,  1.07530797e+00, -4.58863378e-01],
          [

In [72]:
tf.gather(tensor_h, indices=[2,0,2,3,1])

<tf.Tensor: shape=(5, 16, 32, 32, 64), dtype=float32, numpy=
array([[[[[-6.30041242e-01,  1.17947018e+00, -1.20516598e+00, ...,
            2.14079237e+00,  4.60876077e-01, -7.64574409e-01],
          [-1.23745012e+00, -9.90283012e-01,  6.42450273e-01, ...,
            1.30014968e+00, -2.21531123e-01,  1.20414114e+00],
          [-1.68866253e+00,  1.73338461e+00,  8.40698242e-01, ...,
            1.00771906e-02,  5.14728129e-01, -3.48388910e-01],
          ...,
          [-3.05095464e-01, -3.02681357e-01, -1.31952167e+00, ...,
            3.12394090e-02, -2.09495902e+00,  1.35497713e+00],
          [-6.17283702e-01,  6.52985096e-01, -8.66339386e-01, ...,
           -3.23502034e-01, -1.43435881e-01, -8.82932365e-01],
          [ 7.01100707e-01,  6.08502805e-01, -4.78555858e-01, ...,
           -4.52858120e-01,  1.40318722e-01,  2.06754804e+00]],

         [[-2.49203593e-02, -2.84688640e-02, -5.15813351e-01, ...,
            1.95415452e-01,  9.50683892e-01, -8.12854886e-01],
          [-

In [69]:
tf.gather_nd(tensor_h, indices=[[1,1,1],[3,0,2]])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1.7570856, -0.3149678], dtype=float32)>

In [77]:
tensor_h.get_shape()

TensorShape([16, 16, 32, 32, 64])

In [82]:
print(tensor_h.shape)
arr = tf.reshape(tensor_h, (2,2,4194304))
print(arr.shape)

(16, 16, 32, 32, 64)
(2, 2, 4194304)


In [87]:
print(tensor_h.shape)
arr = tf.expand_dims(tensor_h, axis=1)
print(arr.shape)

(16, 16, 32, 32, 64)
(16, 16, 32, 32, 64, 1)


In [88]:
print(arr.shape)
arr2 = tf.squeeze(arr, axis=5)
print(arr2.shape)

(16, 16, 32, 32, 64, 1)
(16, 16, 32, 32, 64)


In [89]:
print(tensor_h.shape)
arr3 = tf.transpose(tensor_h)
print(arr3.shape)

(16, 16, 32, 32, 64)
(64, 32, 32, 16, 16)


In [93]:
print(tensor_h.shape)
arr4 = tf.broadcast_to(tensor_h,shape=[12,16,16,32,32,64])
print(arr3.shape)

(16, 16, 32, 32, 64)
(64, 32, 32, 16, 16)


In [96]:
rand = tf.random.normal([5])
rand.numpy()

array([ 0.98868257,  1.8542291 , -0.22396456,  0.53628665, -0.42257094],
      dtype=float32)

In [102]:
print(rand.shape)
rand2 = tf.broadcast_to(rand,shape=[30,5])
rand2

(5,)


<tf.Tensor: shape=(30, 5), dtype=float32, numpy=
array([[ 0.98868257,  1.8542291 , -0.22396456,  0.53628665, -0.42257094],
       [ 0.98868257,  1.8542291 , -0.22396456,  0.53628665, -0.42257094],
       [ 0.98868257,  1.8542291 , -0.22396456,  0.53628665, -0.42257094],
       [ 0.98868257,  1.8542291 , -0.22396456,  0.53628665, -0.42257094],
       [ 0.98868257,  1.8542291 , -0.22396456,  0.53628665, -0.42257094],
       [ 0.98868257,  1.8542291 , -0.22396456,  0.53628665, -0.42257094],
       [ 0.98868257,  1.8542291 , -0.22396456,  0.53628665, -0.42257094],
       [ 0.98868257,  1.8542291 , -0.22396456,  0.53628665, -0.42257094],
       [ 0.98868257,  1.8542291 , -0.22396456,  0.53628665, -0.42257094],
       [ 0.98868257,  1.8542291 , -0.22396456,  0.53628665, -0.42257094],
       [ 0.98868257,  1.8542291 , -0.22396456,  0.53628665, -0.42257094],
       [ 0.98868257,  1.8542291 , -0.22396456,  0.53628665, -0.42257094],
       [ 0.98868257,  1.8542291 , -0.22396456,  0.53628665, -0.

In [117]:
a = tf.constant([[3,5],[7,9]])
b = tf.constant([[4,6],[8,10]])
print(tf.add(a,b))
print(tf.subtract(a,b))
print(tf.multiply(a,b))
print(tf.divide(a,b))
# print(tf.math.log(a,b))
print(tf.pow(a,b))

tf.Tensor(
[[ 7 11]
 [15 19]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-1 -1]
 [-1 -1]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[12 30]
 [56 90]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.75       0.83333333]
 [0.875      0.9       ]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[        81      15625]
 [   5764801 -808182895]], shape=(2, 2), dtype=int32)


In [118]:
tf.matmul(a,b).numpy()

array([[ 52,  68],
       [100, 132]])

In [136]:
angka = tf.random.normal([3,3])
angka

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.2762783 ,  0.24541017, -0.37032604],
       [ 0.34704176,  0.8820411 , -1.5541447 ],
       [ 0.2788544 , -0.05475575,  0.48389545]], dtype=float32)>

In [139]:
tf.argmax(angka, axis=1)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 1, 2], dtype=int64)>

In [143]:
tf.argmin(angka, axis=None)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 2, 1], dtype=int64)>

In [145]:
reduc = tf.constant([1,2,3,4],shape=[2,2])

In [149]:
print(tf.reduce_sum(reduc, axis=None).numpy())
print(tf.reduce_max(reduc, axis=None).numpy())
print(tf.reduce_min(reduc, axis=None).numpy())
print(tf.reduce_mean(reduc, axis=None).numpy())


10
4
1
2


In [158]:
arra1 = tf.constant([
    [1,2,3],
    [2,4,8],
    [1,3,5],
])
arra2= tf.constant([
    [2,3,5],
    [7,11,13],
    [17,23,29]
])

In [167]:
print(arra1.shape)
print(arra2.shape)
arra_gabung = tf.concat([arra1, arra2], axis=0)
print(arra_gabung.shape)
print(arra_gabung)

(3, 3)
(3, 3)
(6, 3)
tf.Tensor(
[[ 1  2  3]
 [ 2  4  8]
 [ 1  3  5]
 [ 2  3  5]
 [ 7 11 13]
 [17 23 29]], shape=(6, 3), dtype=int32)


In [183]:
print(arra1.shape)
print(arra2.shape)
arra_stack = tf.stack([arra1, arra2], axis=1)
print(arra_stack.shape)
print(arra_stack)

(3, 3)
(3, 3)
(3, 2, 3)
tf.Tensor(
[[[ 1  2  3]
  [ 2  3  5]]

 [[ 2  4  8]
  [ 7 11 13]]

 [[ 1  3  5]
  [17 23 29]]], shape=(3, 2, 3), dtype=int32)


In [184]:
print(arra_stack.shape)
arra_unstack = tf.unstack(arra_stack, axis=1)
print(arra_unstack)

(3, 2, 3)
[<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 4, 8],
       [1, 3, 5]])>, <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  3,  5],
       [ 7, 11, 13],
       [17, 23, 29]])>]


In [186]:
arra_split = tf.split(arra_stack, num_or_size_splits=3)
print(arra_split)

[<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 3, 5]]])>, <tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[ 2,  4,  8],
        [ 7, 11, 13]]])>, <tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[ 1,  3,  5],
        [17, 23, 29]]])>]


In [187]:
tf.sort(arra_gabung)

<tf.Tensor: shape=(6, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 2,  4,  8],
       [ 1,  3,  5],
       [ 2,  3,  5],
       [ 7, 11, 13],
       [17, 23, 29]])>